version: '3'
services:
  newsletter-app:
    image: thebeginner86/newsletter-app:v1.0.2
    ports:
      - 4000:3000
  # newsletter-app:
  #   build: 
  #     context: .
    # ports:
    #   - 4000:3000
  mongodb:
    image: mongo
    ports: 
      - 37017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    container_name: mongodb
    volumes: 
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    ports: 
      - 9081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express
    depends_on: 
      - mongodb
volumes: 
  mongodb-data:
    driver: local
