version: '3'
services:
  newsletter-app:
    image: thebeginner86/newsletter-app:v1.0.3
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    container_name: mongodb
  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    container_name: mongo-express
