# You can skip this file and use generalized cluster made by: kind create cluster --name [name of your cluster you want]

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000